# Generated by Django 6.0.3 on 2026-03-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cpf_alter_user_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('ong', 'ONG'), ('policia', 'Policia')], max_length=10),
        ),
    ]
