# Generated by Django 6.0.3 on 2026-07-25 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('ong', 'ONG'), ('policia', 'Policia')], default='usuario', max_length=10),
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('pix', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ONG', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
