# Generated by Django 6.0.3 on 2026-07-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_tipo_ong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='telefone',
        ),
    ]
