# Generated by Django 6.0.3 on 2026-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_ong_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuário'), ('ong', 'ONG')], default='usuario', max_length=10),
        ),
    ]
