# Generated by Django 6.0.3 on 2026-07-21 15:54

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncias',
            name='cidade',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='condicao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bem / saudável', 'Bem / saudável'), ('Sujo', 'Sujo'), ('Muito magro', 'Muito magro'), ('Fraco / sem forças', 'Fraco / sem forças'), ('Dificuldade para andar', 'Dificuldade para andar'), ('Dificuldade para respirar', 'Dificuldade para respirar'), ('Parece doente', 'Parece doente'), ('Machucado', 'Machucado'), ('Sangrando', 'Sangrando'), ('Osso ou ferida aberta', 'Osso ou ferida aberta'), ('Inchaço ou caroços', 'Inchaço ou caroços'), ('Parasitas', 'Parasitas'), ('Sarna aparente', 'Sarna aparente'), ('Queda de pelo', 'Queda de pelo'), ('Assustado', 'Assustado'), ('Agressivo', 'Agressivo'), ('Muito quieto / parado', 'Muito quieto / parado'), ('Desorientado', 'Desorientado'), ('Perto de trânsito intenso', 'Perto de trânsito intenso')], default='Bem / saudável', max_length=500),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='data_encontro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='midia_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='motivo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('atendimento', 'Atendimento'), ('finalizado', 'Finalizado')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='tipo_animal',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='titulo_caixinha',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncias',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario ID'),
        ),
    ]
