# Generated by Django 6.0.3 on 2026-07-25 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_denuncias_cidade_denuncias_condicao_and_more'),
        ('users', '0004_alter_user_tipo_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncias',
            name='ong_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ong', verbose_name='ONG ID'),
        ),
    ]
