# Generated by Django 6.0.3 on 2026-07-25 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_denuncias_ong_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncias',
            name='data_status_aceito',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
