# Generated by Django 6.0.3 on 2026-08-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_denuncias_data_status_aceito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncias',
            old_name='status',
            new_name='statu',
        ),
    ]
