# Generated by Django 6.0.3 on 2026-08-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_rename_status_denuncias_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncias',
            old_name='statu',
            new_name='status',
        ),
    ]
