# Generated by Django 6.0.3 on 2026-08-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_rename_statu_denuncias_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncias',
            old_name='ong_id',
            new_name='ong',
        ),
        migrations.RenameField(
            model_name='denuncias',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
