# Generated by Django 6.0.3 on 2026-08-07 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_ong_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Desconhecido', max_length=255)),
                ('especie', models.CharField(default='Desconhecido', max_length=255)),
                ('raca', models.CharField(default='Desconhecido', max_length=255)),
                ('idade', models.CharField(default='Desconhecido', max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('status_adocao', models.CharField(choices=[('disponivel', 'disponivel'), ('adotado', 'adotado'), ('em processo', 'em processo')], max_length=50)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ong_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ong', verbose_name='ONG ID')),
            ],
        ),
    ]
