# Generated by Django 6.0.3 on 2026-08-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='ong_id',
            new_name='ong',
        ),
    ]
