# Generated by Django 6.0.3 on 2026-08-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0002_rename_ong_id_animal_ong'),
        ('users', '0005_remove_ong_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ong', verbose_name='ONG'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status_adocao',
            field=models.CharField(choices=[('disponivel', 'disponivel'), ('adotado', 'adotado')], max_length=50),
        ),
    ]
