# Generated by Django 6.0.3 on 2026-08-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0003_alter_animal_ong_alter_animal_status_adocao'),
        ('users', '0005_remove_ong_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ong', verbose_name='ONG'),
            preserve_default=False,
        ),
    ]
