# Generated by Django 6.0.3 on 2026-08-24 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0004_alter_animal_ong'),
        ('users', '0005_remove_ong_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateTimeField(default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adocoes.animal', verbose_name='ÀNIMAL')),
                ('ong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ong', verbose_name='ONG')),
            ],
        ),
    ]
